function Residuals = KellerModelContactBCs(Ml, Mr, modelParams)
% Boundary conditions specified for self-contact at a single point.
% Specifically, we split the problem into three intervals and introduce
% matching conditions. This results in 21 boundary conditions.

% Obtain the relevant model parameters
L = modelParams.L;

Residuals = [Ml(1, 1), ...
             Ml(2, 1), ...
             Ml(3, 1), ...
             Ml(5, 1), ...
             Ml(6, 1), ...
             Mr(4, 2) - (Mr(4, 1) + Mr(9, 1)), ...
             Mr(5, 1), ...
             Mr(2, 1), ...
             Ml(2, 2) - Mr(2, 1), ...
             Ml(5, 2) - Mr(5, 1), ...
             Mr(6, 1) - 0.5*pi, ...
             Ml(6, 2) - 0.5*pi, ...
             Ml(3, 2) - Mr(3, 1), ...
             Ml(7, 2) - Mr(7, 1), ...
             Ml(9, 2) - Mr(9, 1), ...
             Mr(5, 2), ...
             Mr(1, 2) - L, ...
             Mr(6, 2) - L]; % theta3(L) = 0
         
end